---

- name: Assert some variables and ansible os family
  ansible.builtin.assert:
    that:
      - ansible_os_family == "RedHat" or ansible_os_family == "Debian"
    msg: "Unsupported distribution."

- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Import install tasks.
  ansible.builtin.import_tasks:
    file: install.yml

- name: Import configure tasks.
  ansible.builtin.import_tasks:
    file: configure.yml
